version: "3.9"
services:
  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
    depends_on:
      - bfs
      - dfs
    networks:
      - alchemy-net

  bfs:
    build: ./src/backend/bfs
    ports:
      - "8081:8081"
    networks:
      - alchemy-net

  dfs:
    build: ./src/backend/dfs
    ports:
      - "8082:8082"
    networks:
      - alchemy-net

networks:
  alchemy-net:
    driver: bridge
